services:
  - type: web
    name: fastapi-prisma-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m prisma generate
      python prisma_setup.py
      python -m prisma db push
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: file:./prisma/database.db
      - key: PYTHONPATH
        value: .
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: binary